### PR TITLE
`multi_predict()` for glmnet to return mean count

### LINKED ISSUE #63: glmnet: Default to mean count for `multi_predict()`
Both `predict()` and `multi_predict()` have a default of `type = NULL`. For `poisson_reg(engine = "glmnet")`, `predict()` returns the mean count (glmnet's type `"response"`) while `multi_predict()` returns the linear predictor (glmnet's type `"link"`). 

I would expect both to default to the same, and I would expect that to be the mean count. 

Side note: we introduced a prediction type `"linear_pred"` for censored regression, which we might extend to other modes.

``` r
library(poissonreg)
#> Loading required package: parsnip

data(seniors, package = "poissonreg")

spec <- poisson_reg(penalty = 0.1, mixture = 0.3) %>%
  set_engine("glmnet", nlambda = 15)
f_fit <- fit(spec, count ~ ., data = seniors)

# default: type = NULL -> "numeric"
our_pred <- predict(f_fit, seniors, penalty = 0.1)
our_pred
#> # A tibble: 8 × 1
#>   .pred
#>   <dbl>
#> 1 540. 
#> 2 740. 
#> 3 282. 
#> 4 387. 
#> 5  90.7
#> 6 124. 
#> 7  47.4
#> 8  65.0
identical(our_pred, predict(f_fit, seniors, penalty = 0.1, type = "numeric"))
#> [1] TRUE

# default: type = NULL
our_multi_pred <- multi_predict(f_fit, seniors, penalty = 0.1) %>% 
  tidyr::unnest(cols = .pred)
our_multi_pred
#> # A tibble: 8 × 2
#>   penalty .pred
#>     <dbl> <dbl>
#> 1     0.1  6.29
#> 2     0.1  6.61
#> 3     0.1  5.64
#> 4     0.1  5.96
#> 5     0.1  4.51
#> 6     0.1  4.82
#> 7     0.1  3.86
#> 8     0.1  4.17


seniors_x <- model.matrix(~ ., data = seniors[, -4])[, -1]
seniors_y <- seniors$count
glmnet_fit <- glmnet::glmnet(x = seniors_x, y = seniors_y, family = "poisson",
                          alpha = 0.3, nlambda = 15)
waldo::compare(
  our_pred$.pred,
  predict(glmnet_fit, seniors_x, s = 0.1, type = "response") %>% as.vector()
)
#> ✔ No differences

waldo::compare(
  our_multi_pred$.pred,
  predict(glmnet_fit, seniors_x, s = 0.1, type = "link") %>% as.vector()
)
#> ✔ No differences
```

<sup>Created on 2023-01-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by hfrick**
closes  #63

``` r
library(poissonreg)
#> Loading required package: parsnip

data(seniors, package = "poissonreg")

spec <- poisson_reg(penalty = 0.1, mixture = 0.3) %>%
  set_engine("glmnet", nlambda = 15)
f_fit <- fit(spec, count ~ ., data = seniors)

# default: type = NULL -> "numeric"
our_pred <- predict(f_fit, seniors, penalty = 0.1)
our_pred
#> # A tibble: 8 × 1
#>   .pred
#>   <dbl>
#> 1 540. 
#> 2 740. 
#> 3 282. 
#> 4 387. 
#> 5  90.7
#> 6 124. 
#> 7  47.4
#> 8  65.0
identical(our_pred, predict(f_fit, seniors, penalty = 0.1, type = "numeric"))
#> [1] TRUE

# default: type = NULL
our_multi_pred <- multi_predict(f_fit, seniors, penalty = 0.1) %>% 
  tidyr::unnest(cols = .pred)
our_multi_pred
#> # A tibble: 8 × 2
#>   penalty .pred
#>     <dbl> <dbl>
#> 1     0.1 540. 
#> 2     0.1 740. 
#> 3     0.1 282. 
#> 4     0.1 387. 
#> 5     0.1  90.7
#> 6     0.1 124. 
#> 7     0.1  47.4
#> 8     0.1  65.0


seniors_x <- model.matrix(~ ., data = seniors[, -4])[, -1]
seniors_y <- seniors$count
glmnet_fit <- glmnet::glmnet(x = seniors_x, y = seniors_y, family = "poisson",
                          alpha = 0.3, nlambda = 15)
waldo::compare(
  our_pred$.pred,
  predict(glmnet_fit, seniors_x, s = 0.1, type = "response") %>% as.vector()
)
#> ✔ No differences

# This is now also the response aka mean count (instead of the linear predictor)
waldo::compare(
  our_multi_pred$.pred,
  predict(glmnet_fit, seniors_x, s = 0.1, type = "response") %>% as.vector()
)
#> ✔ No differences
```

<sup>Created on 2024-11-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by hfrick** [comment]
CI failure on `oldrel-4` (R 4.0.5) is due to a undeclared dependency of `distributional` on R 4.1 through a use of `|>`. That's been fixed in the dev version of distributional: https://github.com/mitchelloharawild/distributional/commit/2a2db7677e95766dcfaa2864978e9f76640c69cd

CI failure on `devel` is due to C errors when building `MatrixStats` but I am not sure how poissonreg depends on that or what to do about it. Hoping it will resolve itself. If not, it should be a separate PR.
```
> pak::pkg_deps_explain("poissonreg", "matrixStats", dependencies = TRUE)
                                                                          
x matrixStats
```

File: R/poisson_reg-glmnet.R [hunk 1]
```diff
@@ -82,6 +82,13 @@ multi_predict._fishnet <-
       }
     }
 
+    if (is.null(type)) {
+      type <- "numeric"
+    }
+    if (type == "numeric") {
+      dots$type <- "response"
+    }
```
Comment (simonpcouch) [inline R/poisson_reg-glmnet.R:90]:
```suggestion
    if (type == "numeric") {
      # `glmnet:::predict.fishnet()` will receive `type = "response"`
      # via `parsnip:::predict_raw.model_fit` (#89)
      dots$type <- "response"
    }
```

Had to walk myself through the internals here to convince myself that something was actually happening to this list element.

File: NEWS.md [hunk 2]
```diff
@@ -1,8 +1,10 @@
 # poissonreg (development version)
 
+* Predictions via `multi_predict()` for glmnet models now correctly are the mean counts instead of the linear predictor (#89).
```
Comment (simonpcouch) [inline NEWS.md:3]:
```suggestion
* Predictions via `multi_predict()` for glmnet models now correctly default to mean counts instead of the linear predictor (#89).
```

Maybe? Not sure if this is actually the case.

**Review by simonpcouch — APPROVED** [review]
🏄
